use db_reservation ;
DROP PROCEDURE IF EXISTS PI_SALLE; 
DROP PROCEDURE IF EXISTS PI_SALLE_SIMPLE; 
DROP PROCEDURE IF EXISTS PSGetSALLE; 
DROP PROCEDURE IF EXISTS PL_SALLE;
DROP PROCEDURE IF EXISTS PU_SALLE; 
DROP PROCEDURE IF EXISTS PD_SALLE; 