use db_reservation ;
DROP PROCEDURE IF EXISTS PI_RES; 
DROP PROCEDURE IF EXISTS PI_RES_SIMPLE; 
DROP PROCEDURE IF EXISTS PSGet_RES; 
DROP PROCEDURE IF EXISTS PFind_RES;
DROP PROCEDURE IF EXISTS PU_RES; 
DROP PROCEDURE IF EXISTS PD_RES; 