use db_reservation;

DROP PROCEDURE IF EXISTS `PI_MAIL`;
DROP PROCEDURE IF EXISTS `PI_MAIL_SIMPLE`;
DROP PROCEDURE IF EXISTS `PSGet_MAIL`;
DROP PROCEDURE IF EXISTS `PFind_MAIL`;
DROP PROCEDURE IF EXISTS `PU_MAIL`;
DROP PROCEDURE IF EXISTS `PD_MAIL`;