use db_reservation;

CALL PI_INFORMATION(1,"xx.xx@xx.xx" , "DUPOND", "DIDIER", "DIRECTEUR", "SIMPLONSCOOL");
CALL PI_INFORMATION_SIMPLE("test@gmail.com" , "TOTO", "INGALLS", "SOUS CHEF", "DGSI");
CALL PsGetINFORMATION(1);
CALL PSGetINFROMATIONmail("xx.xx@xx.xx");
CALL PL_INFORMATION();
CALL PU_INFORMATION(1 , "xx.TEST@gmail", "DUPONT","DIDIER","PDG","SIMPLONE");
CALL PD_INFORMATION(1);
