use db_reservation ;
DROP PROCEDURE IF EXISTS PI_INFORMATION; 
DROP PROCEDURE IF EXISTS PI_INFORMATION_SIMPLE; 
DROP PROCEDURE IF EXISTS PSGetINFORMATION; 
DROP PROCEDURE IF EXISTS PL_INFORMATION;
DROP PROCEDURE IF EXISTS PU_INFORMATION; 
DROP PROCEDURE IF EXISTS PD_INFORMATION; 