use db_reservation ;
DROP PROCEDURE IF EXISTS PI_ROLE; 
DROP PROCEDURE IF EXISTS PI_ROLE_SIMPLE; 
DROP PROCEDURE IF EXISTS PSGetROLE; 
DROP PROCEDURE IF EXISTS PL_ROLE;
DROP PROCEDURE IF EXISTS PU_ROLE; 
DROP PROCEDURE IF EXISTS PD_ROLE; 

